# Generated by Django 5.1.4 on 2026-05-27 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
