# Generated by Django 5.1.4 on 2026-05-27 03:58

from django.db import migrations


import uuid

def gen_uuid(apps, schema_editor):
    Group = apps.get_model('tracker', 'Group')
    for row in Group.objects.all():
        row.invite_code = uuid.uuid4()
        row.save(update_fields=['invite_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_group_invite_code'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
